# Generated by Django 5.0.6 on 2024-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_api", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
