# Generated by Django 5.0.6 on 2024-06-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_api", "0005_post_scheduled_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="scheduled_time",
        ),
    ]
